---

name: Check Set-Up & Build

# Controls when the action will run.
# yamllint disable-line rule:truthy
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches: [main]
  push:
    branches: [main]

# A workflow run is made up of one or more jobs
# that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks
    # that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access it
      - uses: actions/checkout@v2

      - name: Run yamllint
        uses: actionshub/yamllint@main

      - name: Install Rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          rustup component add clippy
          rustup component add rustfmt
      - name: Check Formatting
        run: |
          cargo nightly fmt -- --check
      - name: Check Clippy
        run: |
          cargo clippy
      - name: Check Build
        run: |
          cargo check
      - name: Run Tests
        run: |
          cargo test